version: "3.8"

services:
  postgresdb:
    image: postgres:13
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=CpDTSTm0Lb0KJEDHevq3
      - POSTGRES_DB=railway
    ports:
      - 5433:7782
    volumes:
      - db:/var/lib/postgresql/data

  app:
    depends_on:
      - postgresdb
    build: ./app
    restart: on-failure
    ports:
      - 6868:8080
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:postgresql://postgres:ydfg9FOXjOp8mqNutvtE@containers-us-west-151.railway.app:7886/railway",
        "spring.datasource.username" : "postgres",
        "spring.datasource.password" : "ydfg9FOXjOp8mqNutvtE",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    volumes:
      - .m2:/root/.
    stdin_open: true
    tty: true

volumes:
  db:
